# Site settings
title: "Saurav's blog"
email: 
description:  
baseurl: ""
url: "whattheblog.github.io"
footnote: "Saurav Dey Â© 2025"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

include:
 - _pages 

collections:
  somefolder:
    output: true
